interface EnvVariables {
  OPENAI_API_KEY: string;
  ASSISTANT_ID: string;
  ELEVENLABS_API_KEY: string;
  ELEVENLABS_VOICE_ID: string;
  CHECK_PHONE_WEBHOOK_URL: string;
  INTERVIEW_HISTORY_WEBHOOK_URL: string;
  DROPBOX_ACCESS_TOKEN: string;
}

export function getEnvVariables(): EnvVariables {
  return {
    OPENAI_API_KEY: process.env.NEXT_PUBLIC_OPENAI_API_KEY || '',
    ASSISTANT_ID: process.env.NEXT_PUBLIC_ASSISTANT_ID || '',
    ELEVENLABS_API_KEY: process.env.NEXT_PUBLIC_ELEVENLABS_API_KEY || '',
    ELEVENLABS_VOICE_ID: process.env.NEXT_PUBLIC_ELEVENLABS_VOICE_ID || '',
    CHECK_PHONE_WEBHOOK_URL: process.env.NEXT_PUBLIC_CHECK_PHONE_WEBHOOK_URL || '',
    INTERVIEW_HISTORY_WEBHOOK_URL: process.env.NEXT_PUBLIC_INTERVIEW_HISTORY_WEBHOOK_URL || '',
    DROPBOX_ACCESS_TOKEN: process.env.NEXT_PUBLIC_DROPBOX_ACCESS_TOKEN || '',
  };
}
